In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv(r"G:\My Drive\Python\project\project\dataSets\taipei_real_estate\a_lvr_land_a.csv") 
# df\

In [36]:
df.describe()
# df.describe(include='all')
# df.columns
# plt.plot(df)
# plt.show()

,鄉鎮市區,交易標的,土地位置建物門牌,土地移轉總面積平方公尺,都市土地使用分區,非都市土地使用分區,非都市土地使用編定,交易年月日,交易筆棟數,移轉層次,...,車位類別,車位移轉總面積平方公尺,車位總價元,備註,編號,主建物面積,附屬建物面積,陽台面積,電梯,移轉編號
count,644,644,644,644,608,1,1,644,644,523,...,197,644,644,440,644,644,644,644,644,229
unique,13,6,630,565,61,1,1,131,36,46,...,7,131,48,81,644,478,204,317,3,214
top,大安區,房地(土地+建物),臺北市文山區忠順街一段２７之２號,2.92,住,the non-metropolis land use district,non-metropolis land use,1120712,土地1建物1車位0,三層,...,坡道平面,0.0,0,其他增建；,serial number,0.0,0.0,0.0,有,028
freq,76,334,4,4,317,1,1,31,244,57,...,121,495,506,68,1,144,418,268,375,4

In [63]:
h=pd.DataFrame(df)
# 單價元平方公尺 總價元 '土地移轉總面積平方公尺' '交易年月日'
# df['總價元']
# df = df.set_index('鄉鎮市區')
# h.groupby('鄉鎮市區')

tprice=h.loc[1:,['鄉鎮市區','總價元','單價元平方公尺','交易年月日']]
tprice
# tprice.plot()

    鄉鎮市區       總價元 單價元平方公尺    交易年月日
1    內湖區     16538       0  1120710
2    內湖區   1400000     NaN  1120711
3    士林區      2339       0  1120706
4    大安區    135558  117877  1120704
5    信義區   1032500  103250  1120712
..   ...       ...     ...      ...
639  中山區  16000000  258148  1080907
640  中山區  16600000  267828  1080910
641  內湖區  26340000  202025  1080812
642  文山區  14880000  170852  1070915
643  文山區  16300000  182176  1070616

[643 rows x 4 columns]